import py7zr
import os
import subprocess
import wget
from playsound import playsound
from threading import Thread
execlocation = os.getcwd()
audiocounter = 1

if os.path.isdir("flashyfiles") == True:
    print("Assets have already been downloaded.")
    print("Entering Macromedia Flash directory...")
    directory2go = "%s\\flashyfiles"%execlocation
else:
        print("Doing initial setup work...")
        os.mkdir("flashyfiles")
        os.chdir("flashyfiles")
        print("Downloading 7z archive with core Macromedia Flash executables...")
        wget.download("https://github.com/ojwatts1999/flashintothepast/raw/flash-repo/coreflashfiles.7z", out="coreflashfiles.7z")
        print("Extracting 7z archive with core Macromedia Flash executables...")
        with py7zr.SevenZipFile("coreflashfiles.7z", 'r') as archive:
            archive.extractall()
        print("Downloading 7z archive with Macromedia Flash executables...")
        wget.download("https://github.com/ojwatts1999/flashintothepast/raw/flash-repo/mmTour.7z", out="mmTour.7z")
        print("Extracting 7z Archive with Macromedia Flash executables...")
        with py7zr.SevenZipFile("mmTour.7z", 'r') as archive:
            archive.extractall()
        print("Downloading 7z archive with audio files...")
        wget.download("https://github.com/ojwatts1999/flashintothepast/raw/flash-repo/audio.7z", out="audio.7z")
        print("Extracting 7z archive with audio files...")
        with py7zr.SevenZipFile("audio.7z", 'r') as archive:
            archive.extractall()
        print("Cleaning up...")
        os.remove("coreflashfiles.7z")
        os.remove("mmTour.7z")
        os.remove("audio.7z")
        print("Entering Macromedia Flash directory...")
        directory2go = "%s\\flashyfiles"%execlocation
        
def audiostart():
    os.chdir(directory2go)
    os.chdir("audio")
    print("Audio 1 starting...")
    playsound('sound (1).wav', False)
    print("Audio 2 starting...")
    playsound('sound (2).wav', False)
    print("Audio 3 starting...")
    playsound('sound (3).wav', False)
    print("Audio 4 starting...")
    playsound('sound (4).wav', False)
    print("Audio 5 starting...")
    playsound('sound (5).wav', False)
    print("Audio 6 starting...")
    playsound('sound (6).wav', False)
    print("Audio 7 starting...")
    playsound('sound (7).wav', False)
    print("Audio 8 starting...")
    playsound('sound (8).wav', False)
    print("Audio 9 starting...")
    playsound('sound (9).wav', False)
    print("Audio 10 starting...")
    playsound('sound (10).wav', False)
    print("Audio 11 starting...")
    playsound('sound (11).wav', False)
    print("Audio 12 starting...")
    playsound('sound (12).wav', False)
    print("Audio 13 starting...")
    playsound('sound (13).wav', False)
    print("Audio 14 starting...")
    playsound('sound (14).wav', False)
    print("Audio 15 starting...")
    playsound('sound (15).wav', False)
    print("Audio 16 starting...")
    playsound('sound (16).wav', False)
    print("Audio 17 starting...")
    playsound('sound (17).wav', False)
    print("Audio 18 starting...")
    playsound('sound (18).wav', False)
    print("Audio 19 starting...")
    playsound('sound (19).wav', False)
    print("Audio 20 starting...")
    playsound('sound (20).wav', False)
    print("Audio 21 starting...")
    playsound('sound (21).wav', False)
    print("Audio 22 starting...")
    playsound('sound (22).wav', False)
    print("Audio 23 starting...")
    playsound('sound (23).wav', False)
    print("Audio 24 starting...")
    playsound('sound (24).wav', False)
    print("Audio 25 starting...")
    playsound('sound (25).wav', False)
    print("Audio 26 starting...")
    playsound('sound (26).wav', False)
    print("Audio 27 starting...")
    playsound('sound (27).wav', False)
    print("Audio 28 starting...")
    playsound('sound (28).wav', False)
    print("Audio 29 starting...")
    playsound('sound (29).wav', False)
    print("Audio 30 starting...")
    playsound('sound (30).wav', False)
    print("Audio 31 starting...")
    playsound('sound (31).wav', False)
    print("Audio 32 starting...")
    playsound('sound (32).wav', False)
    print("Audio 33 starting...")
    playsound('sound (33).wav', False)
    print("Audio 34 starting...")
    playsound('sound (34).wav', False)
    print("Audio 35 starting...")
    playsound('sound (35).wav', False)
    print("Audio 36 starting...")
    playsound('sound (36).wav', False)
    print("Audio 37 starting...")
    playsound('sound (37).wav', False)
    print("Audio 38 starting...")
    playsound('sound (38).wav', False)
    print("Audio 39 starting...")
    playsound('sound (39).wav', False)
    print("Audio 40 starting...")
    playsound('sound (40).wav', False)
    print("Audio 41 starting...")
    playsound('sound (41).wav', False)
    print("Audio 42 starting...")
    playsound('sound (42).wav', False)
    print("Audio 43 starting...")
    playsound('sound (43).wav', False)
    print("Audio 44 starting...")
    playsound('sound (44).wav', False)
    print("Audio 45 starting...")
    playsound('sound (45).wav', False)
    print("Audio 46 starting...")
    playsound('sound (46).wav', False)
    print("Audio 47 starting...")
    playsound('sound (47).wav', False)
    print("Audio 48 starting...")
    playsound('sound (48).wav', False)
    print("Audio 49 starting...")
    playsound('sound (49).wav', False)
    print("Audio 50 starting...")
    playsound('sound (50).wav', False)
    print("Audio 51 starting...")
    playsound('sound (51).wav', False)
    print("Audio 52 starting...")
    playsound('sound (52).wav', False)
    print("Audio 53 starting...")
    playsound('sound (53).wav', False)
    print("Audio 54 starting...")
    playsound('sound (54).wav', False)
    print("Audio 55 starting...")
    playsound('sound (55).wav', False)
    print("Audio 56 starting...")
    playsound('sound (56).wav', False)
    print("Audio 57 starting...")
    playsound('sound (57).wav', False)
    print("Audio 58 starting...")
    playsound('sound (58).wav', False)
    print("Audio 59 starting...")
    playsound('sound (59).wav', False)
    print("Done!")
    return

def runflashfiles():
    print("Starting round!")
    os.chdir(directory2go)
    subprocess.Popen("flash1.exe")
    print("flash1.exe started.")
    subprocess.Popen("flash2.exe")
    print("flash2.exe started.")
    subprocess.Popen("flash3.exe")
    print("flash3.exe started.")
    subprocess.Popen("flash4.exe")
    print("flash4.exe started.")
    subprocess.Popen("flash5.exe")
    print("flash5.exe started.")
    subprocess.Popen("flash6.exe")
    print("flash6.exe started.")
    subprocess.Popen("flash7.exe")
    print("flash7.exe started.")
    subprocess.Popen("flash8.exe")
    print("flash8.exe started.")
    subprocess.Popen("flash9.exe")
    print("flash9.exe started.")
    subprocess.Popen("flash10.exe")
    print("flash10.exe started.")
    subprocess.Popen("flash11.exe")
    print("flash11.exe started.")
    subprocess.Popen("flash12.exe")
    print("flash12.exe started.")
    subprocess.Popen("flash13.exe")
    print("flash13.exe started.")
    os.chdir("mmTour")
    subprocess.Popen("tour.exe")
    print("tour.exe started.")
    print("Starting next round...")
    audiostart()
    runflashfiles()
    return

runflashfiles()
